## 应用服务 WEB 访问端口
#server.port=8080
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.syzy.ebuy.mybatis.entity

web:
  profile: D:\Code\lianxi\dzy\upload\
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebuy
    username: root
    password: root
  web:
    resources:
      static-locations:
        [ "classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","file:${web.profile}"]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 2MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

demo:
    jwt:
      user-secret-key: zhangsanfg
      user-ttl: 7200000
      user-token-name: authentication
    wechat:
      appid:${demo.wechat.appid}
      secret:${demo.wechat.secret}

